### PR TITLE
Split configuration arguments on colons instead of hyphens

### LINKED ISSUE #25: The repository name (setting `repo_name`) cannot contain a hyphen
So I tried to configure my chachacha for my repo and got the following:

```python
$ chachacha config repo_name ewen-lbh/pyrelease
Traceback (most recent call last):
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/bin/chachacha", line 11, in <module>
    sys.exit(main())
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/main.py", line 65, in added
    driver.add_entry("added", changes)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/drivers/kac.py", line 129, in add_entry
    self.write(current=current)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/drivers/kac.py", line 89, in write
    config = self.get_config(init=True)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/drivers/kac.py", line 169, in get_config
    return Configuration.factory(line)
  File "/home/ewen/.cache/pypoetry/virtualenvs/pyrelease-AMrVBIvF-py3.6/lib/python3.6/site-packages/chachacha/configuration.py", line 58, in factory
    configuration[Configuration.conf_map[arg[0]]] = arg[1:]
KeyError: 'l'
```

I hunted down the culprit and saw that you split configuration arguments on hyphens. As both GitHub and Gitlab allow hyphens in usernames and repository names, this will prevent projects and even _entire users_ (like me) to use your project, which is a bummer considering how great of a program this is :D

I propose using `:` instead, which is [not allowed in github usernames](https://user-images.githubusercontent.com/39094199/86517503-aa667780-be29-11ea-8336-d5f7a8d2b3a0.png) and [gitlab usernames](https://user-images.githubusercontent.com/39094199/86403626-61d67f00-bcae-11ea-9f4e-0e0f39b597c1.png)

### PR DESCRIPTION
**Pull request by ewen-lbh**
See #25

Will close #25

### CODE REVIEW

**Comment by ewen-lbh** [comment]
Yeah I need to update and add tests

**Comment by ewen-lbh** [comment]
Hm, weird. The commit message somehow disappeared. I updated tests and fixed the unmarshaling

**Comment by ewen-lbh** [comment]
I also got rid of setup.py since declaring some more stuff in `pyproject.toml` suffices

**Comment by ewen-lbh** [comment]
summoning @aogier in case you forgot & have the time to deal w/ this :)

**Comment by aogier** [comment]
Ehi @ewen-lbh ! Today I'll work on that, seems super promising and I definitely want to have this one. Please note that I removed your `.vscode` and updated gitignores so you'd probably wish to restore it from your latest commit

**Pull request merged**
